### ISSUE TITLE
Trace Completion API 调用失败

### ISSUE THREAD

**Issue by Wadud-Ma** [deepflowio/deepflow-app#137]
{
    "OPT_STATUS": "INTERNAL_SERVER_ERROR",
    "DESCRIPTION": "complete_app_span() missing 1 required positional argument: 'app_spans'"
}

传参self.app_spans后报错
{
    "OPT_STATUS": "INTERNAL_SERVER_ERROR",
    "DESCRIPTION": "\"Model 'AppSpans' has no field named 'tap_side'\""
}

**Comment by JiezengDev** [comment]
+1 
遇到了一样的问题，按照[官方文档](https://deepflow.io/docs/zh/integration/output/query/trace-completion/#%E5%85%A5%E5%8F%82%E8%AF%B4%E6%98%8E) ，请求返回
{
    "OPT_STATUS": "INTERNAL_SERVER_ERROR",
    "DESCRIPTION": "complete_app_span() missing 1 required positional argument: 'app_spans'"
}

deepflow-app日志：
2023-10-31 17:01:04,960 T139969792911168-MainThread ERROR utils.wrapper.129: complete_app_span() missing 1 required positional argument: 'app_spans'
Traceback (most recent call last):
  File "/root/app/common/utils.py", line 104, in wrapper
    response = await function(*args, **kwargs)
  File "/root/app/application/application.py", line 41, in l7_flow_app_tracing
    status, response, failed_regions = await TracingCompletion(
  File "/root/app/application/tracing_completion.py", line 23, in __init__
    self.complete_app_span()
TypeError: complete_app_span() missing 1 required positional argument: 'app_spans'

**Comment by xiaochaoren1** [comment]
能看下请求参数吗，以及使用版本

**Comment by JiezengDev** [comment]
> 能看下请求参数吗，以及使用版本

- 版本： deepflow-app:v6.4.0
- 请求方法: POST  http://${server}:${port}/v1/stats/querier/tracing-completion-by-external-app-spans
- body
```json
{
"max_iteration": 30,
"network_delay_us": 3000000,
"app_spans": [
{
"trace_id": "xx-0ada15c8-471847-70053",
"span_id": "xxx-0ada15c8-471847-70053",
"parent_span_id": "",
"span_kind": 0,
"start_time_us": 1698651000000000,
"end_time_us": 1698651659000000
}
]
}
```

**Comment by xiaochaoren1** [comment]
> * 版本： deepflow-app:v6.4.0
>   按照[官方文档](https://deepflow.io/docs/zh/integration/output/query/trace-completion/#%E5%85%A5%E5%8F%82%E8%AF%B4%E6%98%8E) 配置
> * 请求body
>   {
>   "max_iteration": 30,
>   "network_delay_us": 3000000,
>   "app_spans": [
>   {
>   "trace_id": "xx-0ada15c8-471847-70053",
>   "span_id": "xxx-0ada15c8-471847-70053",
>   "parent_span_id": "",
>   "span_kind": 0,
>   "start_time_us": 1698651000000000,
>   "end_time_us": 1698651659000000
>   }
>   ]
>   }
> * 返回值
>   {
>   "OPT_STATUS": "INTERNAL_SERVER_ERROR",
>   "DESCRIPTION": "complete_app_span() missing 1 required positional argument: 'app_spans'"
>   }
> * deepflow-app日志：
>   2023-10-31 17:01:04,960 T139969792911168-MainThread ERROR utils.wrapper.129: complete_app_span() missing 1 required positional argument: 'app_spans'
>   Traceback (most recent call last):
>   File "/root/app/common/utils.py", line 104, in wrapper
>   response = await function(*args, **kwargs)
>   File "/root/app/application/application.py", line 41, in l7_flow_app_tracing
>   status, response, failed_regions = await TracingCompletion(
>   File "/root/app/application/tracing_completion.py", line 23, in **init**
>   self.complete_app_span()
>   TypeError: complete_app_span() missing 1 required positional argument: 'app_spans'

问题已知晓，会尽快修复，谢谢帮助指出问题，对糟糕的使用体验深感抱歉

**Comment by dundun9** [comment]
> 能看下请求参数吗，以及使用版本

@JiezengDev

**Comment by JiezengDev** [comment]
> > 能看下请求参数吗，以及使用版本
> 
> @JiezengDev

参考这个
 https://github.com/deepflowio/deepflow-app/issues/137#issuecomment-1786807935

**Comment by xiaochaoren1** [comment]
如果着急的话，可以先用v6.2版本

**Comment by xiaochaoren1** [comment]
v6.3版本已修复

**Comment by JiezengDev** [comment]
> v6.3版本已修复

是需要从v6.4降级到v6.3吗？
如果只针对这个接口，能否只对deepflow-app进行版本变更，其他组件版本不变？

**Comment by xiaochaoren1** [comment]
> > v6.3版本已修复
> 
> 是需要从v6.4降级到v6.3吗？ 如果只针对这个接口，能否只对deepflow-app进行版本变更，其他组件版本不变？

只降级deepflow-app组件即可，其他不用降

**Comment by JiezengDev** [comment]
> > > v6.3版本已修复
> > 
> > 
> > 是需要从v6.4降级到v6.3吗？ 如果只针对这个接口，能否只对deepflow-app进行版本变更，其他组件版本不变？
> 
> 只降级deepflow-app组件即可，其他不用降

降级后，请求内容不变，返回值如下，是不是还有其他接口适配问题？

```json
{

"OPT_STATUS": "PARTIAL_RESULT",

"DESCRIPTION": "code: 47, message: Missing columns: 'x_request_id' while processing query: 'WITH toUnixTimestamp64Micro(start_time) AS start_time_us, toUnixTimestamp64Micro(end_time) AS end_time_us SELECT type, req_tcp_seq, resp_tcp_seq, start_time_us, end_time_us, vtap_id, syscall_trace_id_request, syscall_trace_id_response, span_id, parent_span_id, l7_protocol, trace_id, x_request_id, _id, tap_side, if(auto_instance_type_0 IN (0, 255), if(is_ipv4 = 1, IPv4NumToString(ip4_0), IPv6NumToString(ip6_0)), dictGet(flow_tag.device_map, 'name', (toUInt64(auto_instance_type_0), toUInt64(auto_instance_id_0)))) AS resource_gl0_0, if(auto_instance_type_1 IN (0, 255), if(is_ipv4 = 1, IPv4NumToString(ip4_1), IPv6NumToString(ip6_1)), dictGet(flow_tag.device_map, 'name', (toUInt64(auto_instance_type_1), toUInt64(auto_instance_id_1)))) AS resource_gl0_1 FROM flow_log.l7_flow_log PREWHERE ((time >= 1698650997) AND (time <= 1698651662)) AND (trace_id = 'xxx-0ada15c8-471847-70053') LIMIT 100', required columns: 'type' 'span_id' 'start_time' 'trace_id' 'req_tcp_seq' 'ip6_0' 'resp_tcp_seq' 'vtap_id' 'syscall_trace_id_request' 'ip4_1' 'parent_span_id' 'time' '_id' 'end_time' 'auto_instance_type_0' 'ip4_0' 'x_request_id' 'tap_side' 'auto_instance_id_0' 'is_ipv4' 'auto_instance_type_1' 'l7_protocol' 'syscall_trace_id_response' 'ip6_1' 'auto_instance_id_1', maybe you meant: ['type','span_id','start_time','trace_id','req_tcp_seq','ip6_0','resp_tcp_seq','vtap_id','syscall_trace_id_request','ip4_1','parent_span_id','time','_id','end_time','auto_instance_type_0','ip4_0','request_id','tap_side','auto_instance_id_0','is_ipv4','auto_instance_type_1','l7_protocol','syscall_trace_id_response','ip6_1','auto_instance_id_1']",

"DATA": {

"tracing": [

{

"_ids": [

"0"

],

"related_ids": [

"0-base-0"

],

"start_time_us": 1698651000000000,

"end_time_us": 1698651659000000,

"duration": 659000000,

"tap_side": "app",

"l7_protocol": 0,

"l7_protocol_str": "",

"endpoint": "",

"request_type": "",

"request_resource": "",

"response_status": 0,

"flow_id": "0",

"request_id": 0,

"x_request_id": "",

"trace_id": "xxx-0ada15c8-471847-70053",

"span_id": "xxx-0ada15c8-471847-70053",

"parent_span_id": "",

"req_tcp_seq": 0,

"resp_tcp_seq": 0,

"syscall_trace_id_request": "0",

"syscall_trace_id_response": "0",

"syscall_cap_seq_0": 0,

"syscall_cap_seq_1": 0,

"process_id": null,

"vtap_id": 0,

"app_service": "",

"app_instance": "",

"deepflow_span_id": "xxx-0ada15c8-471847-70053",

"deepflow_parent_span_id": ""

}

]

},

"TYPE": "tracing-completion-by-external-app-spans"

}
```

**Comment by xiaochaoren1** [comment]
> > > > v6.3版本已修复
> > > 
> > > 
> > > 是需要从v6.4降级到v6.3吗？ 如果只针对这个接口，能否只对deepflow-app进行版本变更，其他组件版本不变？
> > 
> > 
> > 只降级deepflow-app组件即可，其他不用降
> 
> 降级后，请求内容不变，返回值如下，是不是还有其他接口适配问题？
> 
> ```json
> {
> 
> "OPT_STATUS": "PARTIAL_RESULT",
> 
> "DESCRIPTION": "code: 47, message: Missing columns: 'x_request_id' while processing query: 'WITH toUnixTimestamp64Micro(start_time) AS start_time_us, toUnixTimestamp64Micro(end_time) AS end_time_us SELECT type, req_tcp_seq, resp_tcp_seq, start_time_us, end_time_us, vtap_id, syscall_trace_id_request, syscall_trace_id_response, span_id, parent_span_id, l7_protocol, trace_id, x_request_id, _id, tap_side, if(auto_instance_type_0 IN (0, 255), if(is_ipv4 = 1, IPv4NumToString(ip4_0), IPv6NumToString(ip6_0)), dictGet(flow_tag.device_map, 'name', (toUInt64(auto_instance_type_0), toUInt64(auto_instance_id_0)))) AS resource_gl0_0, if(auto_instance_type_1 IN (0, 255), if(is_ipv4 = 1, IPv4NumToString(ip4_1), IPv6NumToString(ip6_1)), dictGet(flow_tag.device_map, 'name', (toUInt64(auto_instance_type_1), toUInt64(auto_instance_id_1)))) AS resource_gl0_1 FROM flow_log.l7_flow_log PREWHERE ((time >= 1698650997) AND (time <= 1698651662)) AND (trace_id = 'xxx-0ada15c8-471847-70053') LIMIT 100', required columns: 'type' 'span_id' 'start_time' 'trace_id' 'req_tcp_seq' 'ip6_0' 'resp_tcp_seq' 'vtap_id' 'syscall_trace_id_request' 'ip4_1' 'parent_span_id' 'time' '_id' 'end_time' 'auto_instance_type_0' 'ip4_0' 'x_request_id' 'tap_side' 'auto_instance_id_0' 'is_ipv4' 'auto_instance_type_1' 'l7_protocol' 'syscall_trace_id_response' 'ip6_1' 'auto_instance_id_1', maybe you meant: ['type','span_id','start_time','trace_id','req_tcp_seq','ip6_0','resp_tcp_seq','vtap_id','syscall_trace_id_request','ip4_1','parent_span_id','time','_id','end_time','auto_instance_type_0','ip4_0','request_id','tap_side','auto_instance_id_0','is_ipv4','auto_instance_type_1','l7_protocol','syscall_trace_id_response','ip6_1','auto_instance_id_1']",
> 
> "DATA": {
> 
> "tracing": [
> 
> {
> 
> "_ids": [
> 
> "0"
> 
> ],
> 
> "related_ids": [
> 
> "0-base-0"
> 
> ],
> 
> "start_time_us": 1698651000000000,
> 
> "end_time_us": 1698651659000000,
> 
> "duration": 659000000,
> 
> "tap_side": "app",
> 
> "l7_protocol": 0,
> 
> "l7_protocol_str": "",
> 
> "endpoint": "",
> 
> "request_type": "",
> 
> "request_resource": "",
> 
> "response_status": 0,
> 
> "flow_id": "0",
> 
> "request_id": 0,
> 
> "x_request_id": "",
> 
> "trace_id": "xxx-0ada15c8-471847-70053",
> 
> "span_id": "xxx-0ada15c8-471847-70053",
> 
> "parent_span_id": "",
> 
> "req_tcp_seq": 0,
> 
> "resp_tcp_seq": 0,
> 
> "syscall_trace_id_request": "0",
> 
> "syscall_trace_id_response": "0",
> 
> "syscall_cap_seq_0": 0,
> 
> "syscall_cap_seq_1": 0,
> 
> "process_id": null,
> 
> "vtap_id": 0,
> 
> "app_service": "",
> 
> "app_instance": "",
> 
> "deepflow_span_id": "xxx-0ada15c8-471847-70053",
> 
> "deepflow_parent_span_id": ""
> 
> }
> 
> ]
> 
> },
> 
> "TYPE": "tracing-completion-by-external-app-spans"
> 
> }
> ```

main 已修复，还是用main吧，只降deepflow-app可能会引发未知问题
