### ISSUE TITLE
获取调用日志(l7_flow_log)返回的请求信息中的_id字段都是一样的值

### ISSUE THREAD

**Issue by xiaoyuan2019** [deepflowio/deepflow-app#299]
通过sql语句从server接口获取的调用日志列表中的每个元素的_id字段是一样的，这个字段应该是唯一的才对，然后用这个_id字段去app的接口获取火焰图数据时，返回数据都为空，请帮忙看下，比较急，感谢！
![image](https://github.com/user-attachments/assets/49c49312-a6d7-4436-883d-6ca8e22da1d9)

**Comment by xiaoyuan2019** [comment]
server接口：url=http://xxxxx:20416//v1/query/
app接口：url=http://10.186.200.51:20418/v1/stats/querier/L7FlowTracing
获取调用日志的sql语句：body={'db': 'flow_log', 'sql': 'SELECT toString(start_time) AS `start_time`, toString(end_time) AS `end_time`, auto_instance_0, auto_instance_1, Enum(l7_protocol) AS `l7_protocol_name`, request_type AS `request_type`, endpoint AS `endpoint`, request_domain AS `request_domain`, request_resource AS `request_resource`, Enum(response_status) AS `response_status`, response_code AS `response_code`, response_exception AS `response_exception`, Enum(observation_point) AS `observation_point_name`, `response_duration` AS `response_delay`, auto_instance_id_0, auto_instance_id_1, flow_id, agent_id,toString(_id) AS `_id`, Enum(auto_instance_type_0) AS `auto_instance_type_0_name`,Enum(auto_instance_type_1) AS `auto_instance_type_1_name`,trace_id,Enum(signal_source) AS `signal_source_name` FROM l7_flow_log WHERE time>= 1729741723 AND time<= 1729742623 LIMIT 1000'}
获取火焰图数据的sql语句：body={'_id': 7429187055690117000, 'TIME_START': 1729741723, 'TIME_END': 1729742623, 'DATABASE': 'flow_log', 'TABLE': 'l7_flow_log', 'DEBUG': True}
接口请求方式：result = requests.post(url=url, headers=headers, data=body, timeout=10)

**Comment by taloric** [comment]
可以确认下 requests.post 获取到的原始 _id 内容，以及要确保使用 toString(_id)，返回前端最好直接使用string，这种情况一般是从后端应用返回到前端过程中丢失精度，数据本身是没错的

**Comment by xiaoyuan2019** [comment]
@taloric 非常感谢，确实需要转换成string到前端才能保住精度。

**Comment by taloric** [comment]
@xiaoyuan2019 ok，那我关闭此 issue，有其他问题的话可以随时重新打开
